import type { CoverageZone, GeoPoint } from '@/modules/coverage/domain/coverage';
import type {
  CatalogRepository,
  PackageRecord,
  ProviderRecord,
} from '../application/catalog-repository';

/**
 * DEMO DATA — not real companies, prices, coverage, or SLAs.
 * Every record has `isDemo: true` and is labelled "DEMO" in the UI. Used until the
 * Postgres-backed catalog exists, and later as seed data for local development.
 */

const d = (iso: string) => new Date(iso);

const providers: ProviderRecord[] = [
  {
    id: 'demo-prov-001',
    slug: 'demo-provider-001',
    displayName: 'Demo Provider 001',
    legalName: 'PT Demo Provider Satu (data demo)',
    description:
      'Provider demo untuk menguji alur marketplace. Fokus pada layanan fiber untuk rumah tangga di area contoh Jakarta Selatan dan Depok.',
    technologies: ['FIBER'],
    supportHours: 'Setiap hari 08.00–22.00 WIB (demo)',
    slaSummary: 'Contoh SLA: target pemulihan gangguan 1×24 jam (data demo)',
    supportPhone: null,
    supportEmail: 'support@demo-provider-001.invalid',
    website: null,
    serviceAreaNames: ['Area demo Jakarta Selatan', 'Area demo Depok (terbatas)'],
    listingPriority: 0,
    installationInfo:
      'Teknisi akan menghubungi Anda untuk konfirmasi jadwal. Survei teknis dapat diperlukan sebelum pemasangan.',
    verificationStatus: 'VERIFIED',
    verifiedAt: d('2026-09-01T03:00:00Z'),
    deletedAt: null,
    isDemo: true,
  },
  {
    id: 'demo-prov-002',
    slug: 'demo-provider-002',
    displayName: 'Demo Provider 002',
    legalName: 'PT Demo Provider Dua (data demo)',
    description:
      'Provider demo dengan kombinasi fiber dan fixed wireless. Cocok untuk menguji perbandingan teknologi dan hasil "perlu survei".',
    technologies: ['FIBER', 'FIXED_WIRELESS'],
    supportHours: '24 jam (demo)',
    slaSummary: null,
    supportPhone: null,
    supportEmail: 'halo@demo-provider-002.invalid',
    website: null,
    serviceAreaNames: ['Area demo Jakarta Pusat–Selatan', 'Area demo Depok (perlu survei)'],
    listingPriority: 0,
    installationInfo:
      'Untuk area berstatus "Perlu survei", teknisi melakukan survei lokasi terlebih dahulu sebelum pembayaran.',
    verificationStatus: 'VERIFIED',
    verifiedAt: d('2026-08-20T03:00:00Z'),
    deletedAt: null,
    isDemo: true,
  },
  {
    // Deliberately UNDER_REVIEW: proves unverified providers never reach the marketplace.
    id: 'demo-prov-003',
    slug: 'demo-provider-003',
    displayName: 'Demo Provider 003',
    legalName: 'PT Demo Provider Tiga (data demo)',
    description: 'Provider demo yang masih dalam proses verifikasi — tidak boleh tampil publik.',
    technologies: ['FIXED_WIRELESS'],
    supportHours: '—',
    slaSummary: null,
    supportPhone: null,
    supportEmail: null,
    website: null,
    serviceAreaNames: ['Area demo Jabodetabek'],
    listingPriority: 0,
    installationInfo: '—',
    verificationStatus: 'UNDER_REVIEW',
    verifiedAt: null,
    deletedAt: null,
    isDemo: true,
  },
];

const base = {
  status: 'PUBLISHED' as const,
  validUntil: null,
  isDemo: true,
  taxIncluded: false,
  contractMonths: 0,
  lastPriceVerifiedAt: d('2026-09-15T03:00:00Z'),
};

const packages: PackageRecord[] = [
  {
    ...base,
    id: 'demo-pkg-101',
    providerId: 'demo-prov-001',
    name: 'Demo Rumah 30',
    slug: 'demo-provider-001-rumah-30',
    description: 'Paket demo untuk browsing dan streaming ringan 1–3 perangkat.',
    downloadMbps: 30,
    uploadMbps: 30,
    technology: 'FIBER',
    monthlyPrice: 199_000,
    installationFee: 150_000,
    activationFee: 0,
    routerIncluded: true,
    fupPolicy: null,
    slaSummary: null,
    supportHours: '08.00–22.00 WIB',
    estInstallationDaysMin: 2,
    estInstallationDaysMax: 5,
    publishedAt: d('2026-09-15T03:00:00Z'),
    features: [{ label: 'Router', value: 'Dipinjamkan selama berlangganan (demo)' }],
  },
  {
    ...base,
    id: 'demo-pkg-102',
    providerId: 'demo-prov-001',
    name: 'Demo Rumah 75',
    slug: 'demo-provider-001-rumah-75',
    description: 'Paket demo untuk keluarga dengan banyak perangkat dan video call.',
    downloadMbps: 75,
    uploadMbps: 75,
    technology: 'FIBER',
    monthlyPrice: 299_000,
    installationFee: 150_000,
    activationFee: 0,
    routerIncluded: true,
    fupPolicy: null,
    slaSummary: null,
    supportHours: '08.00–22.00 WIB',
    estInstallationDaysMin: 2,
    estInstallationDaysMax: 5,
    publishedAt: d('2026-09-15T03:00:00Z'),
    features: [{ label: 'Router', value: 'Dual-band, dipinjamkan (demo)' }],
  },
  {
    ...base,
    id: 'demo-pkg-103',
    providerId: 'demo-prov-001',
    name: 'Demo Kerja 150',
    slug: 'demo-provider-001-kerja-150',
    description: 'Paket demo untuk kerja dari rumah dan upload file besar.',
    downloadMbps: 150,
    uploadMbps: 150,
    technology: 'FIBER',
    monthlyPrice: 449_000,
    installationFee: 0,
    activationFee: 50_000,
    contractMonths: 12,
    routerIncluded: true,
    fupPolicy: null,
    slaSummary: 'Contoh SLA bisnis rumahan (demo)',
    supportHours: '24 jam',
    estInstallationDaysMin: 3,
    estInstallationDaysMax: 7,
    publishedAt: d('2026-09-15T03:00:00Z'),
    features: [{ label: 'IP publik', value: 'Opsional (demo)' }],
  },
  {
    ...base,
    id: 'demo-pkg-201',
    providerId: 'demo-prov-002',
    name: 'Demo Fiber 50',
    slug: 'demo-provider-002-fiber-50',
    description: 'Paket fiber demo dengan harga sudah termasuk pajak.',
    downloadMbps: 50,
    uploadMbps: 25,
    technology: 'FIBER',
    monthlyPrice: 277_500,
    installationFee: 200_000,
    activationFee: 0,
    taxIncluded: true,
    routerIncluded: true,
    fupPolicy: null,
    slaSummary: null,
    supportHours: '24 jam',
    estInstallationDaysMin: 1,
    estInstallationDaysMax: 4,
    publishedAt: d('2026-09-10T03:00:00Z'),
    features: [],
  },
  {
    ...base,
    id: 'demo-pkg-202',
    providerId: 'demo-prov-002',
    name: 'Demo Fiber 100',
    slug: 'demo-provider-002-fiber-100',
    description: 'Paket fiber demo untuk gaming dan streaming 4K.',
    downloadMbps: 100,
    uploadMbps: 50,
    technology: 'FIBER',
    monthlyPrice: 366_300,
    installationFee: 200_000,
    activationFee: 0,
    taxIncluded: true,
    routerIncluded: true,
    fupPolicy: null,
    slaSummary: null,
    supportHours: '24 jam',
    estInstallationDaysMin: 1,
    estInstallationDaysMax: 4,
    publishedAt: d('2026-09-10T03:00:00Z'),
    features: [],
  },
  {
    ...base,
    id: 'demo-pkg-203',
    providerId: 'demo-prov-002',
    name: 'Demo Wireless 20',
    slug: 'demo-provider-002-wireless-20',
    description: 'Paket fixed wireless demo untuk area yang belum terjangkau fiber.',
    downloadMbps: 20,
    uploadMbps: 5,
    technology: 'FIXED_WIRELESS',
    monthlyPrice: 222_000,
    installationFee: 350_000,
    activationFee: 0,
    taxIncluded: true,
    routerIncluded: false,
    fupPolicy: 'Contoh FUP: kecepatan turun ke 5 Mbps setelah 300 GB/bulan (demo)',
    slaSummary: null,
    supportHours: '24 jam',
    estInstallationDaysMin: 3,
    estInstallationDaysMax: 10,
    publishedAt: d('2026-09-10T03:00:00Z'),
    features: [{ label: 'Perangkat', value: 'Antena outdoor, dibeli putus (demo)' }],
  },
  {
    // Expired: proves expired packages are not listed.
    ...base,
    id: 'demo-pkg-204',
    providerId: 'demo-prov-002',
    name: 'Demo Promo Lama',
    slug: 'demo-provider-002-promo-lama',
    description: 'Paket demo yang sudah melewati masa berlaku.',
    downloadMbps: 40,
    uploadMbps: 20,
    technology: 'FIBER',
    monthlyPrice: 150_000,
    installationFee: 0,
    activationFee: 0,
    routerIncluded: true,
    fupPolicy: null,
    slaSummary: null,
    supportHours: '24 jam',
    estInstallationDaysMin: 1,
    estInstallationDaysMax: 4,
    publishedAt: d('2026-01-01T03:00:00Z'),
    validUntil: d('2026-06-30T16:59:59Z'),
    features: [],
  },
  {
    ...base,
    id: 'demo-pkg-301',
    providerId: 'demo-prov-003',
    name: 'Demo Unverified 50',
    slug: 'demo-provider-003-unverified-50',
    description: 'Tidak boleh tampil: provider belum terverifikasi.',
    downloadMbps: 50,
    uploadMbps: 10,
    technology: 'FIXED_WIRELESS',
    monthlyPrice: 99_000,
    installationFee: 0,
    activationFee: 0,
    routerIncluded: false,
    fupPolicy: null,
    slaSummary: null,
    supportHours: '—',
    estInstallationDaysMin: 1,
    estInstallationDaysMax: 2,
    publishedAt: d('2026-09-01T03:00:00Z'),
    features: [],
  },
];

const box = (south: number, north: number, west: number, east: number): GeoPoint[] => [
  { lat: north, lng: west },
  { lat: north, lng: east },
  { lat: south, lng: east },
  { lat: south, lng: west },
];

const zones: CoverageZone[] = [
  {
    id: 'demo-zone-101',
    providerId: 'demo-prov-001',
    strategy: 'POLYGON',
    result: 'AVAILABLE',
    lastVerifiedAt: d('2026-09-01T03:00:00Z'),
    polygons: [[box(-6.3, -6.2, 106.75, 106.85)]],
  },
  {
    id: 'demo-zone-102',
    providerId: 'demo-prov-001',
    strategy: 'RADIUS',
    result: 'LIMITED',
    lastVerifiedAt: d('2026-08-15T03:00:00Z'),
    center: { lat: -6.4025, lng: 106.7942 },
    radiusM: 3_000,
  },
  {
    id: 'demo-zone-201',
    providerId: 'demo-prov-002',
    strategy: 'POLYGON',
    result: 'AVAILABLE',
    lastVerifiedAt: d('2026-08-20T03:00:00Z'),
    polygons: [[box(-6.27, -6.15, 106.78, 106.9)]],
  },
  {
    id: 'demo-zone-202',
    providerId: 'demo-prov-002',
    strategy: 'RADIUS',
    result: 'REQUIRES_SURVEY',
    lastVerifiedAt: d('2026-07-01T03:00:00Z'),
    center: { lat: -6.4025, lng: 106.7942 },
    radiusM: 5_000,
  },
  {
    id: 'demo-zone-203',
    providerId: 'demo-prov-002',
    strategy: 'POLYGON',
    result: 'EXCLUDED',
    lastVerifiedAt: d('2026-08-20T03:00:00Z'),
    polygons: [[box(-6.235, -6.225, 106.8, 106.81)]],
  },
  {
    id: 'demo-zone-301',
    providerId: 'demo-prov-003',
    strategy: 'POLYGON',
    result: 'AVAILABLE',
    lastVerifiedAt: d('2026-09-01T03:00:00Z'),
    polygons: [[box(-6.7, -6.0, 106.5, 107.1)]],
  },
];

/** Locations offered as one-click examples on the coverage page. */
export const DEMO_LOCATIONS = [
  { label: 'Contoh: Kebayoran Baru', lat: -6.244, lng: 106.799 },
  { label: 'Contoh: Depok', lat: -6.4025, lng: 106.7942 },
  { label: 'Contoh: Bogor', lat: -6.595, lng: 106.8166 },
] as const;

export const demoCatalogRepository: CatalogRepository = {
  listProviders: async () => providers,
  listPackages: async () => packages,
  listActiveZones: async () => zones,
};
