import { PERMISSIONS, ROLE_PERMISSIONS, ROLES, type RoleKey } from './rbac';

const ABBR: Record<RoleKey, string> = {
  SUPER_ADMIN: 'SA',
  ADMIN: 'AD',
  CUSTOMER_SUPPORT: 'CS',
  FINANCE: 'FI',
  SALES: 'SL',
  PROVIDER_OWNER: 'PO',
  PROVIDER_ADMIN: 'PA',
  PROVIDER_SALES: 'PS',
  PROVIDER_TECHNICIAN: 'PT',
  CUSTOMER: 'CU',
  REFERRAL_PARTNER: 'RP',
};

/** Renders docs/06-rbac-matrix.md from the code matrix (single source of truth). */
export function renderRbacMarkdown(): string {
  const roles = Object.keys(ROLES) as RoleKey[];
  const lines: string[] = [
    '# 06 — RBAC Matrix',
    '',
    '<!-- GENERATED by `npm run docs:rbac` from src/modules/auth/domain/rbac.ts — do not edit by hand. -->',
    '',
    'Every permission is enforced server-side in application use cases (`can()` / `authorize()` /',
    '`scopeFor()`); hiding UI is never the control. Scopes: **any** = platform-wide,',
    "**provider** = only the actor's provider, **own** = only the actor's own resources.",
    '',
    '## Roles',
    '',
    '| Code | Role | Scope | Description |',
    '| ---- | ---- | ----- | ----------- |',
    ...roles.map((r) => `| ${ABBR[r]} | ${r} | ${ROLES[r].scope} | ${ROLES[r].description} |`),
    '',
    '## Permissions',
    '',
    `| Permission | Description | ${roles.map((r) => ABBR[r]).join(' | ')} |`,
    `| ---------- | ----------- | ${roles.map(() => ':-:').join(' | ')} |`,
    ...PERMISSIONS.map(
      (p) =>
        `| \`${p.key}\` | ${p.description} | ${roles
          .map((r) => (ROLE_PERMISSIONS[r].includes(p.key) ? '✓' : ''))
          .join(' | ')} |`,
    ),
    '',
    '## Additional rules enforced in code',
    '',
    '- Provider roles grant nothing unless the user has an ACTIVE `provider_users` membership.',
    '- Money-moving approvals (refund, payout) also require a different approver than the requester (four-eyes).',
    '- `PAID` / `PAYMENT_FAILED` order states can only be set by the SYSTEM actor (verified webhook).',
    '- Platform role changes are audited as `user_role_changed` with before/after.',
    '',
  ];
  return lines.join('\n');
}
